# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d581bbb2-07ce-4ac2-b8b2-9fa65370ca1f";
      fsType = "ext4";
    };

  fileSystems."/mnt/vault" = {
    device = "/dev/disk/by-uuid/bff7ee91-9014-43c5-94af-089b35ecdf27";
    fsType = "ext4";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6f995d8b-73b6-4ee4-b35c-7443f8d0db14"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
